version: '3'

volumes:
  node_modules:
    driver: 'local'
services:
  admin:
    build:
      context: ./
      dockerfile: ./infrastructure/development/nuxtjs/Dockerfile
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    command: >
      bash -c "yarn install &&
      yarn dev"

  nginx:
    image: nginx:latest
    depends_on:
      - admin
    environment:
      APP: admin
    volumes:
      - ./infrastructure/development/nginx/nginx_admin.conf.template:/etc/nginx/conf.d/default.conf
      - ./infrastructure/development/nginx/.htpasswd:/etc/nginx/.htpasswd
    ports:
      - "8000:80"
