version: 0.2

env:
  variables:
    DOCKER_LOGIN_ID: docker_login_id
    DOCKER_LOGIN_PASSWORD: docker_login_password
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login --username ${DOCKER_LOGIN_ID} --password ${DOCKER_LOGIN_PASSWORD}
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
      - APP_REPOSITORY_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_APP_REPO_NAME}
      - WEB_REPOSITORY_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_NGINX_REPO_NAME}
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo Build pwd `pwd`
      - IMAGE_TAG1=BUILD_`date '+%Y-%m-%d_%H%M%S'`
      - IMAGE_TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo "version":"$IMAGE_TAG"

  build:
    commands:
      - echo Build started on `date`
      - sed -i 's/"git_revision".*/"git_revision":\ '\"$IMAGE_TAG\"',/' app/static/version.json
      - echo Building the Docker image...
      - echo $IMAGE_API_REPO_NAME:$IMAGE_TAG
      - echo $IMAGE_NGINX_REPO_NAME:$IMAGE_TAG
      - docker build -t ${APP_REPOSITORY_URI}:latest -f infrastructure/${DEPLOY}/Dockerfile .
      - docker build -t ${WEB_REPOSITORY_URI}:latest -f infrastructure/${DEPLOY}/nginx/Dockerfile .
      - docker tag ${APP_REPOSITORY_URI}:latest ${APP_REPOSITORY_URI}:${IMAGE_TAG}
      - docker tag ${WEB_REPOSITORY_URI}:latest ${WEB_REPOSITORY_URI}:${IMAGE_TAG}
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image
      - docker push ${APP_REPOSITORY_URI}:${IMAGE_TAG}
      - docker push ${APP_REPOSITORY_URI}:latest
      - docker push ${WEB_REPOSITORY_URI}:${IMAGE_TAG}
      - docker push ${WEB_REPOSITORY_URI}:latest
      - cat infrastructure/${DEPLOY}/taskdef.json.template | sed -e s@\<IMAGE_NGINX_NAME\>@$WEB_REPOSITORY_URI:$IMAGE_TAG@ -e s@\<IMAGE_API_NAME\>@$APP_REPOSITORY_URI:$IMAGE_TAG@ > infrastructure/${DEPLOY}/taskdef.json
      - cat infrastructure/${DEPLOY}/taskdef.json
artifacts:
  base-directory: infrastructure/${DEPLOY}
  files:
    - appspec.yml
    - taskdef.json

version: 0.2
